"""Sangbog-pakke: akkordteori, templates, UG-parsing, layout, rendering, store og CLI.

Eksporterer det offentlige API som tidligere levede i add_song.py, så
add_song.py og øvrige scripts kan importere herfra uændret.
"""

from .chords import (
    ACCIDENTAL,
    CHORD_TYPES,
    FLATS,
    INSTRUMENTS,
    MAX_FRET,
    NOTE_SEMI,
    SHARPS,
    STRING_OPEN,
    build_all_voicings_dbs,
    build_voicings_db,
    extract_chord_names,
    generate_voicings,
    parse_chord_name,
    parse_transpose,
    shift_note,
    transpose_chord,
    transpose_content,
)
from .cli import main
from .layout import (
    LINES_PER_PAGE,
    count_lines,
    decide_layout,
    is_tab_section,
    paginate_sections,
    parse_sections,
    section_line_count,
    split_mixed,
)
from .render import (
    chord_positions_align,
    content_to_html,
    group_lines,
    is_chord_annotation_line,
    is_chord_only_line,
    make_song_html,
    parse_chord_positions,
    render_chord_lines,
    render_chord_lyric_line,
    render_section,
)
from .store import (
    DOWNLOADS_DIR,
    INDEX_FILE,
    SONGS_DATA,
    SONGS_DIR,
    artist_sort_key,
    load_songs,
    process_file,
    processed_sources,
    rebuild_index,
    save_songs,
    slugify,
)
from .templates import (
    CHORD_DIAGRAM_JS,
    CHORD_DIAGRAM_STYLE,
    make_chord_diagram_html,
)
from .ug import extract_ug_data, fetch_page, get_song_info, unwrap_view_source

__all__ = [
    "ACCIDENTAL",
    "CHORD_DIAGRAM_JS",
    "CHORD_DIAGRAM_STYLE",
    "CHORD_TYPES",
    "DOWNLOADS_DIR",
    "FLATS",
    "INDEX_FILE",
    "INSTRUMENTS",
    "LINES_PER_PAGE",
    "MAX_FRET",
    "NOTE_SEMI",
    "SHARPS",
    "SONGS_DATA",
    "SONGS_DIR",
    "STRING_OPEN",
    "artist_sort_key",
    "build_all_voicings_dbs",
    "build_voicings_db",
    "chord_positions_align",
    "content_to_html",
    "count_lines",
    "decide_layout",
    "extract_chord_names",
    "extract_ug_data",
    "fetch_page",
    "generate_voicings",
    "get_song_info",
    "group_lines",
    "is_chord_annotation_line",
    "is_chord_only_line",
    "is_tab_section",
    "load_songs",
    "make_chord_diagram_html",
    "make_song_html",
    "main",
    "paginate_sections",
    "parse_chord_name",
    "parse_chord_positions",
    "parse_sections",
    "parse_transpose",
    "process_file",
    "processed_sources",
    "rebuild_index",
    "render_chord_lines",
    "render_chord_lyric_line",
    "render_section",
    "save_songs",
    "section_line_count",
    "shift_note",
    "slugify",
    "split_mixed",
    "transpose_chord",
    "transpose_content",
    "unwrap_view_source",
]
